### ISSUE TITLE
Empty module

### ISSUE THREAD

**Issue by Ocramius** [EmanueleMinotto/EmbedlyModule#1]
Module provides no functionality :trollface:

**Comment by gianarb** [comment]
:100: This code is very clean

**Comment by EmanueleMinotto** [comment]
![haters_gonna_hate_15](https://cloud.githubusercontent.com/assets/417201/6099266/15c8efac-aff4-11e4-8e2d-3b7c0bffd9bd.jpg)

Now you can open issues (please) :P

**Comment by Ocramius** [comment]
:+1:
