### ISSUE TITLE
Always require an `$httpClient`

### ISSUE THREAD

**Issue by Ocramius** [EmanueleMinotto/EmbedlyModule#4]
Simply always assume that there must be an `$httpClient` for the configured service name, and all this will be unnecessary/simpler: https://github.com/EmanueleMinotto/EmbedlyModule/blob/edc01b752ef68f824fa2b0ecbab453eada63e45b/src/EmbedlyModule/Service/ClientFactory.php#L26

**Comment by EmanueleMinotto** [comment]
Another Guzzle client (already configured with particular configuration, events, etc...) can be used there, then the intention is:
- if `$config['embedly']['http_client'] => null` then the [default HTTP client](https://github.com/EmanueleMinotto/Embedly/blob/master/Client.php#L45) is used
- if `$config['embedly']['http_client'] => 'service_alias'` then that service is used

Isn't this the right way to implement it?

**Comment by Ocramius** [comment]
> if `$config['embedly']['http_client'] => null` then the default HTTP client is used

Just set your default one (always) there, and that's it :-)
Never allow it to be `null` is what I mean: less decision paths, less knowledge overload, less debugging.

**Comment by EmanueleMinotto** [comment]
Ok, should be done.

I'll keep this issue open because tests are still working with the `null` value ( maybe I need to reproduce an application inside tests, or something else... I'll look for a solution :+1: )

Thanks :)
